# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - deploy

variables:
  DOTNET_VERSION: 8.0

build_fe_borrower_project:
  stage: test
  image: node:22.13.0
  cache:
    paths:
      - node_modules/
  before_script:
    - source ~/.profile
    - source ~/.bashrc
    - export PATH="$PATH:~/.nvm/versions/node/v22.13.0/bin"
  script:
    - cd ./plsh-fe-borrower
    - yarn install
    - npm run build
  only:
    - merge_requests
    - client/borrower/develop


build_fe_librarian_project:
  stage: test
  image: node:22.13.0
  cache:
    paths:
      - node_modules/
  before_script:
    - source ~/.profile
    - source ~/.bashrc
    - export PATH="$PATH:~/.nvm/versions/node/v22.13.0/bin"
  script:
    - cd ./plsh-fe-librarian
    - yarn install
    - npm run build
  only:
    - merge_requests
    - client/librarian/develop

build_be:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - echo "Restoring .NET dependencies"
    - dotnet restore
    - echo "Building the application"
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/
      - obj/
  only:
    - merge_requests
    - server/develop

test_be:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - echo "Running tests"
    - dotnet test --configuration Release
  dependencies:
    - build_be
  only:
    - merge_requests
    - server/develop

deploy_be:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: deploy
  script:
    - echo "Publishing the application"
    - dotnet publish --configuration Release --output ./publish
    - echo "Migrating the database"
    - dotnet ef database update --connection "$DefaultConnection" --project ./Data --startup-project ./API
    - echo "Deploying the application"
    - scp -r ./publish ubuntu@ec2-54-252-159-167.ap-southeast-2.compute.amazonaws.com:/var/www/PLBH_App

  only:
    - merge_requests
    - server/develop
